variable "env" {}
variable "vpc" {}
variable "tags" {}
variable "default_vpc_id"  {}
variable "default_route_table" {}
variable "docdb" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}
variable "alb" {}
variable "app" {}
variable "bastion_cidr" {}
